spring.application.name=transactions-importer
spring.mongodb.uri=mongodb://localhost:27017/transactions-importer
spring.data.mongodb.auto-index-creation=true
management.endpoints.web.exposure.include=health,info